#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the alternatingCharacters function below.
def alternatingCharacters(s):
    a = s[0]
    temp = 0
    count = 0
    for i in range(1,len(s)):
        b = s[i]
        if a!=b:
            a = s[i]
            temp += 1
            continue
        elif a==b:
            count += 1
            continue
    if temp==len(s)-1:
        return 0
    elif temp!=len(s)-1:
        return count

q = int(input())
for i in range(q):
    s = input()
    result = alternatingCharacters(list(s))
    print(result)
